trial_name: dnerf
defaults:
  - base.yaml
model:
  dynamic_fields:
    deform_net:
      name: deformation_DNeRF
      d_time: 1
      d_in: 3
      multires: 0
      depth: 8
      width: 128
      skips: [4,]
