trial_name: dynerf
defaults:
  - base.yaml
model:
  dynamic_fields:
    deform_dim: 64
    hyper_net:
      name: hyper_cond_network
      d_in: ${model.dynamic_fields.deform_dim}
      d_out: ${model.dynamic_fields.deform_dim}
      multires_out: 0
