trial_name: hexplanes
defaults:
  - base.yaml
model:
  dynamic_fields:
    sdf_net:
      d_in_1: 0
      name: SDFNetworkGrid
      anneal_trip: one
      bicubic: false

      n_frames: 100
      resfield_layers: []
      composition_rank: 10
      d_out: 129
      d_hidden: 128
      n_layers: 3
      skip_in: [8]
      multires: 0
      multires_topo: 0
      bias: 0.5
      scale: 1.0
      geometric_init: True
      weight_norm: False
      inside_outside: False

      grid_encoder:
        name: hexplane_encoder #triplane_encoder
        resolution: 128
        channels: 16
        box_warp: 3
        d_hidden: ${model.dynamic_fields.sdf_net.d_hidden}
        n_frames: ${n_frames}


system:
  loss:
    tv_reg: [5000, 10.0]
